export const STOCK_MOST_ACTIVE_REQUEST = 'STOCK_MOST_ACTIVE_REQUEST';
export const STOCK_MOST_ACTIVE_SUCCESS = 'STOCK_MOST_ACTIVE_SUCCESS';
export const STOCK_MOST_ACTIVE_FAIL = 'STOCK_MOST_ACTIVE_FAIL';

export const STOCK_GAINERS_REQUEST = 'STOCK_GAINERS_REQUEST';
export const STOCK_GAINERS_SUCCESS = 'STOCK_GAINERS_SUCCESS';
export const STOCK_GAINERS_FAIL = 'STOCK_GAINERS_FAIL';

export const STOCK_LOSERS_REQUEST = 'STOCK_LOSERS_REQUEST';
export const STOCK_LOSERS_SUCCESS = 'STOCK_LOSERS_SUCCESS';
export const STOCK_LOSERS_FAIL = 'STOCK_LOSERS_FAIL';

export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST';
export const STOCK_DETAILS_SUCCESS = 'STOCK_DETAILS_SUCCESS';
export const STOCK_DETAILS_FAIL = 'STOCK_DETAILS_FAIL';

export const STOCK_NEWS_REQUEST = 'STOCK_NEWS_REQUEST';
export const STOCK_NEWS_SUCCESS = 'STOCK_NEWS_SUCCESS';
export const STOCK_NEWS_FAIL = 'STOCK_NEWS_FAIL';

export const STOCK_HOLDING_REQUEST = 'STOCK_HOLDING_REQUEST';
export const STOCK_HOLDING_SUCCESS = 'STOCK_HOLDING_SUCCESS';
export const STOCK_HOLDING_FAIL = 'STOCK_HOLDING_FAIL';

export const STOCK_BUY_REQUEST = 'STOCK_BUY_REQUEST';
export const STOCK_BUY_SUCCESS = 'STOCK_BUY_SUCCESS';
export const STOCK_BUY_FAIL = 'STOCK_BUY_FAIL';

export const STOCK_SELL_REQUEST = 'STOCK_SELL_REQUEST';
export const STOCK_SELL_SUCCESS = 'STOCK_SELL_SUCCESS';
export const STOCK_SELL_FAIL = 'STOCK_SELL_FAIL';

export const STOCK_PORTFOLIO_REQUEST = 'STOCK_PORTFOLIO_REQUEST';
export const STOCK_PORTFOLIO_SUCCESS = 'STOCK_PORTFOLIO_SUCCESS';
export const STOCK_PORTFOLIO_FAIL = 'STOCK_PORTFOLIO_FAIL';

export const STOCK_ORDER_LIST_REQUEST = 'STOCK_ORDER_LIST_REQUEST';
export const STOCK_ORDER_LIST_SUCCESS = 'STOCK_ORDER_LIST_SUCCESS';
export const STOCK_ORDER_LIST_FAIL = 'STOCK_ORDER_LIST_FAIL';

export const STOCK_CHART_DATA_REQUEST = 'STOCK_CHART_DATA_REQUEST';
export const STOCK_CHART_DATA_SUCCESS = 'STOCK_CHART_DATA_SUCCESS';
export const STOCK_CHART_DATA_FAIL = 'STOCK_CHART_DATA_FAIL';
