export const STOCK_GAINERS_REQUEST = 'STOCK_GAINERS_REQUEST';
export const STOCK_GAINERS_SUCCESS = 'STOCK_GAINERS_SUCCESS';
export const STOCK_GAINERS_FAIL = 'STOCK_GAINERS_FAIL';

export const STOCK_LOSERS_REQUEST = 'STOCK_LOSERS_REQUEST';
export const STOCK_LOSERS_SUCCESS = 'STOCK_LOSERS_SUCCESS';
export const STOCK_LOSERS_FAIL = 'STOCK_LOSERS_FAIL';

export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST';
export const STOCK_DETAILS_SUCCESS = 'STOCK_DETAILS_SUCCESS';
export const STOCK_DETAILS_FAIL = 'STOCK_DETAILS_FAIL';

export const STOCK_NEWS_REQUEST = 'STOCK_NEWS_REQUEST';
export const STOCK_NEWS_SUCCESS = 'STOCK_NEWS_SUCCESS';
export const STOCK_NEWS_FAIL = 'STOCK_NEWS_FAIL';
